### ISSUE TITLE
Input 컴포넌트

### ISSUE THREAD

**Issue by mibu119** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#1]
## 배경

-유저가 string이나 number형식으로 된 값을 직접 채워 넣을 수 있는 form 컴포넌트입니다. 

## TODO

- [x] input type을 email, password, text, number, hidden 중에 설정할 수 있습니다.
- [x] input이 bottom-border-line만 있는 것 또는 기본 형태 둘 중 하나를 선택할 수 있습니다.
- [x] border가 none인 형태를 선택할 수 있습니다.
- [x] input의 placeholder 값을 설정할 수 있습니다.
