### ISSUE TITLE
userInfo 컴포넌트 수정

### ISSUE THREAD

**Issue by mibu119** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#106]
## 배경

- 마이페이지에서 userinfo를 클릭할시에 다시 같은 페이지로 이동하지 못하도록 해야함.
- userinfo의 아바타와 정보 사이 간격이 좁음
- storybook args에서 실제 id가 노출되어 있음.

## TODO

- [x] userinfo 컴포넌트에 ismypage props 추가
- [x] ismypage일 경우 페이지 이동 막기
- [x] 아바타와 정보 사이 간격 sm => md로 수정
- [x] storybook id args 변경
