### ISSUE TITLE
게시글 수정 페이지 구현

### ISSUE THREAD

**Issue by HY219** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#110]
## 배경

- 이미 등록했던 게시글을 수정할 수 있습니다.

## TODO

 - [ ] Header 구성
   - [ ] 뒤로가기 아이콘(`<`), 채널명, 수정 버튼
   - [ ]  Page Layout 컴포넌트 이용 
- [ ] 제목과 내용 수정
  - [ ] Text 컴포넌트를 이용
- [ ] 변경된 이미지 파일로 업로드
  - [ ] 이미지 추가 `Icon` 클릭 시 파일 변경
  - [ ] 이미지 미리보기 띄우기
- [ ] 수정 버튼 클릭 시, api에 요청 보내기
<img width="215" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun/assets/82134668/6229e549-e742-4bd9-b1d5-bebce9174100">
