### ISSUE TITLE
main에서 최신화된 정보 회원가입 페이지에 업데이트

### ISSUE THREAD

**Issue by oridori2705** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#113]
## 배경

- 이미 PR이 올라간 상태에서 현재 git pull을 받아오면 에러가 발생해 main에서 필요한 컴포넌트나 파일들을 못가져오는 문제
- 쿼리키를 상수로 보관해야 함
- 회원 가입 뒤로가기 키 적용 (useLayout에서 라우터 적용 함)
- 회원가입 버튼 중앙 정렬 해결

## TODO

- [x] 사용중인 쿼리키 상수로 통합 관리
- [x] 회원가입 뒤로가기 키 적용
- [x] 회원가입 버튼 중앙 정렬 

## ETC
git pull이 안되는 문제때문에 다시 브랜치를 만들어서 수정해야 함
```
fatal: 'main' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

![image](https://github.com/prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun/assets/90139306/af3f0cd8-45c0-4cf7-85fa-db496e0d11e3)
