### ISSUE TITLE
accountpage, 비밀번호 변경 페이지, 계정 수정페이지 리팩토링

### ISSUE THREAD

**Issue by mibu119** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#150]
## 배경

- main branch에 merge 된 공통 컴포넌트로 수정하고, 최신화된 상태에서 담당 페이지 테스트 필요

## TODO

- [ ] alert나 디자인이 없는 요소들을 main branch에 merge 된 공통 컴포넌트로 대체합니다.
- [ ] 각 페이지의 중복 코드나 필요없는 부분을 제거 혹은 수정합니다.
- [ ] validation이나 query key를 상수로 변경합니다.
