### ISSUE TITLE
네비게이션에서 현재 로그인 상태와 현재 알림상태 구현

### ISSUE THREAD

**Issue by oridori2705** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#154]
## 배경

- 로그인했을 때 자신이 로그인되었다는 표시가 있어야할 것 같다고 생각함
- 팀원들과 의견을 나누고, 네비게이션 바 하단에 마이페이지 아이콘을 로그인했을 때는 자신의 아이콘으로 변경할 수 있도록 함

- 네비게이션바에서 현재 알람이 왔는지 빠르게 확인가능하도록 뱃지 컴포넌트 활용

## TODO

- [ ] 네비게이션 바가 있는 페이지에서는 모두 현재 알람 목록 API 요청 수행
- [ ] 알람목록 데이터에서 만약 seen 값이 false로 하나라도 있는 경우 검사를 중단하고, 네비게이션 바에 알람 뱃지를 띄움
- [ ] 네비게이션 바가 있는 페이지에서 자신의 프로필 이미지를 마이페이지 아이콘 대신 볼 수 있도록 구현
