### ISSUE TITLE
tailwind.config 테마 형식 수정

### ISSUE THREAD

**Issue by mibu119** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#18]
## 배경

- 테일윈드 css 공식 문서에서 추천하는 형식으로 color와 font 형식을 수정

## TODO

- [x] tailwind.config.js theme의 color gray scale을 수정합니다.
- [x] color의 meaningful color 이름을 수정합니다. red => error, green => success, light-green => online
- [x] font family 이름 LINE => sans, Sigmar => logo로 수정
