### ISSUE TITLE
다크모드 시 색상 문제 및 브라우저 타이틀 버그

### ISSUE THREAD

**Issue by oridori2705** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#195]
## 배경

- 다크모드시 검색창의 text color 가  검은색으로 잘 보이지 않는 문제
- 메시지 페이지 다크모드 색상 변경
- 브라우저 타이틀 꼬이는 문제 -> 계속해서 이전 타이틀을 보여줌 

## TODO

- [x] 다크 모드일 때 검색페이지의 text color 다르게 처리
- [x] 메시지 페이지 다크모드일 때 스타일 수정
- [ ] 브라우저 타이틀 문제 해결 -> 웹환경에서는 잘되는데 인스타 외부 링크에서는 이전 페이지의 이름을 타이틀에 띄움
![image](https://github.com/prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun/assets/90139306/e1bd4b6d-19a8-4326-9f4d-816589412a3d)
