### ISSUE TITLE
Image 컴포넌트 구현

### ISSUE THREAD

**Issue by oridori2705** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#20]
## 배경

- 아바타 컴포넌트, 
- 커버 이미지 컴포넌트,
- 게시글 이미지 컴포넌트,
- 이미지 미리보기 컴포넌트 등에 쓰일 이미지 컴포넌트 구현

## TODO

- [x] 이미지 lazy 기능 구현 ( IntersectionObserver )
- [x] 이미지 크기 ['small','medium','large', 'halfFull','full','srceen','auto',] 가능  
- [x] 이미지 ['cover', 'fill', 'contain'] 가능
