### ISSUE TITLE
Button 컴포넌트 구현

### ISSUE THREAD

**Issue by oridori2705** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#24]
## 배경

- 로그인 버튼
- 회원가입 버튼
- svg 컴포넌트를 포함한 버튼
- 텍스트만 있는 버튼
- 팔로잉 버튼 ( 사용자 목록에서)
- 팔로우 버튼 (사용자 목록에서) 등을 위한 버튼 컴포넌트 구현

## TODO

- [x] 버튼에 loading값을 주고 스피너 컴포넌트가 작동해야함
- [x] children 에서는 icon 컴포넌트 혹은 텍스트를 가져올 수 있어야 함
- [x] fullwidth값이 true일 경우 좌우 공간을 모두 차지함.
- [x] disabled 값이 true일 경우 버튼이 비활성화 되어야함
- [x] button 요소의 type을 지정가능해야함 - button, submit
- [x] 색상은 className으로 컴포넌트 사용자가 지정한다.

## ETC

Spinner 컴포넌트와 Icon 컴포넌트가 merge 되었을 때 진행하면 더 좋겠다고 판단해서 진행 전 입니다.
