### ISSUE TITLE
Text 컴포넌트 수정

### ISSUE THREAD

**Issue by mibu119** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#28]
## 배경

- 알람 컴포넌트와 채팅 컴포넌트를 고려해야한다는 피드백을 받았습니다.

## TODO

- [x] 배경 색깔이나 border radius를 상위 컴포넌트에서 자유롭게 설정할 수 있도록 props를 변경합니다.
- [x] stories의 color variants를 제거합니다.
- [x] fontSize => size로 수정합니다.
- [x] TextVariants => textVariants로 수정 (컴포넌트가 아니므로 케이스 변경)
- [x] div, span, p 태그 중 변경할 수 있습니다.
- [x] 폰트 패밀리를 변경할 수 있습니다.
