### ISSUE TITLE
Avatar 컴포넌트 구현

### ISSUE THREAD

**Issue by oridori2705** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#4]
## 배경

재사용 가능한 Avartar 컴포넌트 구현

## TODO

- [x] 채널 로고가 들어가는 SVG 컴포넌트가 들어갈 수 있는 컴포넌트
- [x] 사용자의 프로필 이미지가 들어갈 수 있는 컴포넌트
- [x] SVG일 때는 배경 색상을 넣을 수 있어야 함 (채널이 활성화일 때 비활성화 일 때)
