### ISSUE TITLE
extraInfo 컴포넌트 구현

### ISSUE THREAD

**Issue by mibu119** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#45]
## 배경

- 목록이나 사용자 정보에 주요 정보 외 기타 정보들이 같은 스타일과 형식으로 자주 사용되어 컴포넌트를 구현하기로 함.
![스크린샷 2023-12-31 오후 4 13 53](https://github.com/prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun/assets/114740795/7d3fdefc-9e3c-40fc-9f0d-fcaa54d8df92)

## TODO

- [x] 더미데이터를 만들어서 데이터가 모두 잘 출력되는지 확인합니다.
- [x] map 또는 단일 문자열로 제작할 수 있도록 합니다.
- [x] map인 경우에는 마지막 칸에 '・' 기호가 안 붙도록 합니다.
