### ISSUE TITLE
UserInfo 컴포넌트 구현

### ISSUE THREAD

**Issue by mibu119** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#48]
## 배경

- 댓글, 게시글 목록, 게시글 상세페이지에 중복으로 사용되어 컴포넌트화를 결정함

## TODO

- [x] 완성된 공통 컴포넌트들을 활용하여 조합합니다. (Avartar, Text, Group)
- [x] data 중 user, post, comment의 user profile, user 이름, post/comment 생성일시의 데이터를 props로 전달할 수 있습니다.
- [x] 유틸 함수로 게시글 생성 시간을 계산하는 함수를 추가합니다.
