### ISSUE TITLE
NavigationBar 컴포넌트 구현

### ISSUE THREAD

**Issue by HY219** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#49]
## 배경
- 원하는 페이지로 빠르게 이동할 수 있게 해주는 네비게이션 컴포넌트입니다. 홈 버튼, 메시지 버튼, 알림 버튼, 마이페이지 버튼을 담고 있는 공간입니다.

## TODO
- [x] footer에 홈, 메시지, 알림, 마이페이지 버튼 구현
- [x] 버튼 클릭 시 페이지 이동
- [x] storybook 연결
<br>

- [x] 검색 아이콘 추가
- [x] hover && 페이지 진입 시 디자인 추가
- [x] footer 디자인 변경 (회색x)
