### ISSUE TITLE
input, text, extrainfo 컴포넌트 스타일 refactor

### ISSUE THREAD

**Issue by mibu119** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#58]
## 배경

- tailwind config에 새로 올라온 공통 스타일로 모두 리팩토링해야함

## TODO

- [x] input 컴포넌트를 리팩토링 합니다.
- [x] text 컴포넌트를 리팩토링 합니다.
- [x] extarinfo 컴포넌트를 리팩토링 합니다.
