### ISSUE TITLE
Text 컴포넌트 구현

### ISSUE THREAD

**Issue by mibu119** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#6]
## 배경

- 공통으로 사용될 Text 컴포넌트입니다. type, color, weight 등을 props로 넘겨줄 수 있습니다.

## TODO

- [x] 내용을 넣어서 출력할 수 있습니다.
- [x] 컴포넌트 변수의 default 값이 있습니다.
- [x] 글씨 색깔을 설정할 수 있습니다.
- [x] 글씨 크기를 설정할 수 있습니다.
- [x] 글씨 굵기를 설정할 수 있습니다.
- [x] 글씨 데코레이션을 설정할 수 있습니다.
- [x] story를 생성합니다.

## ETC

#12
