### ISSUE TITLE
Badge 컴포넌트 구현

### ISSUE THREAD

**Issue by oridori2705** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#63]
## 배경

- 사용자의 로그인 상태와 채팅방 알림, 모든 알림을 표현하기위한 Badge 컴포넌트 구현
- 로그인Badge일 때와 알림Badge일 때를 구분해야하므로 `badgeType: online | offline | alarm` 속성으로 구분함
- absolute로 top-left/top-right/bottom-left/bottom-right를 모두 선택할 수 있어야 함
- alarm의 상태는 `isActive : true/false`
- online과 offline은 isActive가 무조건 true이고, 색상만 변경된다.
- 색상은 컴포넌트 내에서 alarmType에 따라 강제로 지정된다.
- 로그인일 때는 초록색 원형이 출력되어야 함
- 로그아웃일 때는 회색 원형이 출력되어야 함
- 알림일 때는 빨간색 원형이 출력되어야 함
- 각기 다른 크기의 badge가 필요할 가능성이 있음(아바타, 아이콘)

## TODO

- [x] badgeType에 따라 다른 색상으로 된 원형을 출력하는 기능 구현
- [x] badgeType이 online일 때와 offline일 때는 무조건 isActive가 true가 되게 하는 기능 (초록 원형, 회색 원형)
- [x] badgeType이 alarm일 때 isActive가 true면 빨간 원형을 출력하고 false면 아무것도 출력하지 않게 하는 기능
- [x] badge의 크기를 조절할 수 있을 때 badge의 위치 또한 조정가능할 수 있게 해야함
