### ISSUE TITLE
Button 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by oridori2705** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#66]
## 배경

- tailwind.confing에 설정한 값들로 컴포넌트 스타일 재수정
- 버튼이 hover될 때 text-color가 안바뀌는 문제
- disabled 되었을 때 hover가 기능하는 문제

## TODO

- [x] hover:text-white가 적용이 안되는 문제 해결
- [x] disabled에서는 hover가 작동하지 않도록 구현
- [x] 크기나 색상 값은 tailwind.config에서 사용되는 단위로 재구성(디자인 통일)
