### ISSUE TITLE
Avatar 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by oridori2705** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#67]
## 배경

- tailwind.confing에 설정한 값들로 컴포넌트 스타일 재수정
- Avatar 크기 수정 기능 문제

## TODO

- [x] 크기나 색상 값은 tailwind.config에서 사용되는 단위로 재구성(디자인 통일)
- [x] Avatar의 크기를 className으로 지정할 때 잘못 들어가는 문제 해결
- [x] Avatar는 이미지가 드래그 안되도록 설정 (추후 슬라이딩 기능에 사용돼서)
