### ISSUE TITLE
SearchPage 기능 구현

### ISSUE THREAD

**Issue by Heeeera** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#74]
## 배경
- 포스트 및 사용자를 검색할 수 있는 검색 페이지가 있어야 합니다.

## TODO
- [ ] `Input` 컴포넌트를 활용하여 Search Bar를 만듭니다.
- [ ] `Tab` 컴포넌트를 활용하여 검색 결과를 보여줍니다.
  - [ ] 포스트 - 사진이 있는 경우, 사진이 없는 경우 레이아웃 구분
  - [ ] 사용자 - `Avatar`, `ExtraInfo` 컴포넌트 활용
