### ISSUE TITLE
Register 페이지 구현

### ISSUE THREAD

**Issue by oridori2705** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#77]
## 배경

- 로그인 페이지에서 회원가입 버튼을 누르면 이동하는 회원가입 페이지 구현
- 회원가입 API 요청을 수행
- Input 컴포넌트, Text 컴포넌트, Button 컴포넌트 활용
- 헤더에서 뒤로가기 버튼 사용가능

## TODO

- [x] input 컴포넌트를 이용해서 데이터를 입력할 수 있게하고, 버튼을 누르면 회원가입 API 요청 기능 구현
- [x] 헤더에서 뒤로가기 버튼을 만들고 이전 페이지로 가는 기능 구현
- [x] 비밀번호확인 기능 구현
- [x] 회원가입 버튼 시 모든 값이 있는지 검증 구현
- [x] 올바른 이메일 형식인지 검증 구현
- [x] 이메일 중복확인 기능 구현
- [x] 올바른 이메일이면 중복확인 버튼이 활성화되고, 중복확인 버튼을 누르면 결과가 출력된다. 이후 Input데이터를 바꾸면 다시 올바른 이메일 형식인지 검증하는 절차로 이루어지는 기능을 구현

### 1. axios가 설치되어있지 않은데 이를 통합할 파일을 구축해야함 
예를 들어 아래와 같음
```
axios.defaults.baseURL = 'https://api.example.com';
axios.defaults.headers.common['Authorization'] = AUTH_TOKEN;
axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';
```
[axios 인스턴스](https://velog.io/@kcj_dev96/axios-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4-%EC%83%9D%EC%84%B1%EA%B3%BC-%ED%97%A4%EB%8D%94-%EC%84%A4%EC%A0%95)

### 2. API로 받아오는 response 타입은 다들 어떻게 저장했는지 통일해야함
예를 들어 src/common/api/types.ts에 모든 타입을 넣음

### 3. 현재 Group에서 direction을 'col'로 주었을 때 align-items : flex-start 기본값으로 인해 만약 group 내의 요소의 갯수가 다르게 되면 너비를 자동적으로 못맞추는 현상이 생김
![image](https://github.com/prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun/assets/90139306/fe91423f-0c26-40df-8edb-18f0838b50cc)

**이를 해결하기 위해 제가 추측하는 2가지가 있음**

1. Group 컴포넌트의 align의 값을 item-stretch값이 될 수 있도록 함
기본값이 stretch인데 현재 Group컴포넌트의 기본값은 flex-start임
className으로 커스텀하려했으나 적용이 안됨. 이는 아래와 같은 이유로 추측됨
```
<div
      className={cn(
        className,
        groupVariants({
          direction,
          position,
          align,
          inline,
          noWrap,
          grow: grow && !inline,
        }),
      )}
      style={{ gap: groupSpacing }}
      {...props}
    >
```
위 코드에서 className이 twmerge 될 때 맨 앞에 있어 우선순위가 낮음

2.  코드를 아래와 같이 작성하는 방법

![image](https://github.com/prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun/assets/90139306/9139661a-3801-4119-ba3c-bbaee18bfbc1)

이와 같이 작성한 이유는
현재 Group 컴포넌트는 너비 혹은 높이가 없어서 Group내의 요소 중 가장 큰 너비 혹은 높이로 결정이 됨.
그래서 이를 className으로 너비를 결정시켜 원하는 요소의 너비를 늘릴 수 있음

![image](https://github.com/prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun/assets/90139306/8279462c-89cc-4b35-b2eb-b3cc4a66246f)

### 4. React Query를 사용하는 페이지 혹은 컴포넌트는 storybook에서 출력안되는 오류
![image](https://github.com/prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun/assets/90139306/69cd1875-2299-47f1-9fb1-8997710362b3)

위 오류는 useMutation 훅을 사용할 때 애플리케이션에 QueryClient가 설정되어 있지 않아서 발생하는 것
설정하려면 storybook에 설정을 따로 해줘야 함
`.storybook/preview.js` 에서 수행해야하는 것으로 예상함
