### ISSUE TITLE
axios 설치 및 localStorage 구축, axios 인스턴스 설정

### ISSUE THREAD

**Issue by oridori2705** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#86]
## 배경

- axios 사용을 위한 axios 설치
- axios 인스턴스 설정
- 토큰값을 가져오기위해 localStorage 이용
- Base  URL을 env에 저장 후 사용

## TODO

- [x] axios 설치
- [x] axios 인스턴스 파일 생성 및 구축
- [x] axios 토큰 값 localStorage에서 가져오는 기능 구현
- [x] localStorage 기능 구현
- [x] env 설정

## ETC

[axios 인스턴스 참고 자료](https://velog.io/@rudans987/axios-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4-%EC%82%AC%EC%9A%A9%EB%B2%95)

[LocalStrage 예제](https://blog.banksalad.com/tech/typescript-local-storage/)

[axios 헤더 설정](https://velog.io/@kcj_dev96/axios-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4-%EC%83%9D%EC%84%B1%EA%B3%BC-%ED%97%A4%EB%8D%94-%EC%84%A4%EC%A0%95)

### **LocalStorage를 사용한 이유**

> 과거엔 클라이언트 측에 정보를 저장할 때 쿠키를 주로 사용하곤 했습니다. 쿠키를 사용하는 게 데이터를 클라이언트 측에 저장할 수 있는 유일한 방법이었을 때는 이 방법이 타당했지만, 지금은modern storage APIs를 사용해 정보를 저장하는 걸 권장합니다. 모든 요청마다 쿠키가 함께 전송되기 때문에, (특히 mobile data connections에서) 성능이 떨어지는 원인이 될 수 있습니다. 정보를 클라이언트 측에 저장하려면 Modern APIs의 종류인 [웹 스토리지 API](https://developer.mozilla.org/ko/docs/Web/API/Web_Storage_API) (localStorage와 sessionStorage) 와 [IndexedDB](https://developer.mozilla.org/ko/docs/Web/API/IndexedDB_API) 를 사용하면 됩니다.

[MDN 참고링크](https://developer.mozilla.org/ko/docs/Web/HTTP/Cookies#%ED%95%A8%EA%BB%98_%EC%B0%B8%EA%B3%A0%ED%95%A0_%EB%82%B4%EC%9A%A9)
