### ISSUE TITLE
게시글 작성 페이지 구현

### ISSUE THREAD

**Issue by HY219** [prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun#98]
## 배경

- 각 채널에 일치하는 페이지에 게시글이 업로드 될 수 있도록, 제목과 내용을 작성하고 이미지를 추가하여 게시글을 작성할 수 있습니다.

## TODO

- [x] Header 구성
  - [x] 뒤로가기 아이콘(`<`), 채널명, 완료 버튼
  - [x]  Page Layout 컴포넌트 이용 
- [x] 제목과 내용 작성
  - [x] Text 컴포넌트를 이용
- [x] 이미지 추가
  - [x] 이미지 추가 `button` 클릭 시 파일 추가 
  - [x] 이미지 미리보기 띄우기
  - [x] 이미지 제목 띄우기
- [ ] 특정 체널에 포스트 작성
  - [ ] 완료 버튼 클릭 시, api에 요청 보내기
- [x] `HomePage`에 글 작성 버튼 생성

<img width="275" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun/assets/82134668/6c6fc45d-9866-44cb-ab57-bc0436ba4d45">

## ETC
<img width="718" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC5_Owhat_Byunghyun/assets/82134668/c7d2c57d-91fc-47e4-aa73-1cae2c0f9514">
